name: 'Hello World'
description: 'Greet someone'
  who:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: docker run --rm busybox env
